name: duckdb_dbt_project
version: '1.0'
config-version: 2
require-dbt-version: [">=1.10.0", "<2.0.0"]

profile: duckdb_dbt_project

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt-packages"
  - "logs"

models:
  duckdb_dbt_project:
    +schema: models
    +materialized: table

seeds:
  duckdb_dbt_project:
    +schema: raw
    health_data:
      readmissions_seed:
        +column_types:
          "Year": varchar
          "Strata": varchar
          "Strata Name": varchar
          "County": varchar
          "Total Admits (ICD-9)": varchar
          "30-day Readmits (ICD-9)": varchar
          "30-day Readmission Rate (ICD-9)": varchar
          "Total Admits (ICD-10)": varchar
          "30-day Readmits (ICD-10)": varchar
          "30-day Readmission Rate (ICD-10)": varchar