name: duckdb_dbt_project
version: '1.0'
config-version: 2
require-dbt-version: [">=1.10.0", "<2.0.0"]
profile: duckdb_dbt_project

# Snapshots disabled for static data (avoids overhead on repeated builds)
snapshots:
  +enabled: false

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  duckdb_dbt_project:
    +materialized: table
    staging:
      +materialized: view  # Lightweight
    marts:
      +materialized: table  # Persistent for dashboard

seeds:
  duckdb_dbt_project:
    +schema: seeds
    health_data:
      readmissions_seed:
        +column_types:
          Year: integer
          Strata: varchar
          "Strata Name": varchar
          County: varchar
          "Total Admits (ICD-9)": varchar
          "30-day Readmits (ICD-9)": varchar
          "30-day Readmission Rate (ICD-9)": varchar
          "Total Admits (ICD-10)": varchar
          "30-day Readmits (ICD-10)": varchar
          "30-day Readmission Rate (ICD-10)": varchar