duckdb_dbt_project:  
  target: dev        
  outputs:
    dev:
      type: duckdb
      path: data/dev_duckdb.db  
      schema: dev            # Results in schemas like dev_raw, dev_marts
      threads: 4             

    prod:
      type: duckdb
      path: /app/data/my_duckdb.db 
      schema: analytics      
      threads: 4